### ISSUE TITLE
AMD RX 570 - 60,00 Hashrate, MH/s ???

### ISSUE THREAD

**Issue by kungfumasterv11** [Claymore-Dual/Claymore-Dual-Miner#14]
![hashrate](https://user-images.githubusercontent.com/60443440/73383748-fe00f200-42da-11ea-8b1c-4be8f9095e3f.png)
You HASHRATE Table = AMD RX 570 - 60,00 Hashrate, MH/s - Realy? Bug?..Sory my bad englsh.

**Comment by Claymore-Dual** [comment]
Thanks for participating, I fixed it!
